version: "3.9"  # optional since v1.27.0
services:
  clamd:
    image: clamav/clamav:0.104
#    ports:
#      - "3310:3310"
  redis:
    image: redis:6.2.6-bullseye

  clamav-scanservice:
    build: clamav-scanservice
#    ports:
#      - "8082:80"
    links:
      - clamd
      - redis

  proxy:
    image: nginx
    volumes:
      - ./nginx-templates:/etc/nginx/templates
    ports:
      - "8081:8080"
    links:
      - clamav-scanservice

